services:
  - type: web
    name: lyricmindai
    env: python
    plan: free
    buildCommand: ""
    startCommand: python app.py
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
